spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todo_project?serverTimezone=Asia/Seoul
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

    show-sql: true
    open-in-view: false

    hibernate:
      ddl-auto: create

  main:
    allow-circular-references: true

jwt:
  token:
    header: Authorization
    secret: ENC(J+nDUsXGhoG3RcAPZikqHFVJzZN8aDUAGJnUSPq2LtIE6eZKi0Rv9/+vDADvx8bsVAQZSiZ5d1V2jChOkLz+bf7FvDGt7cCEoHmt4oZjBwg/oA/TbDAn5DduMJ+6WPZ33Iwo0GE9uvU8+BofFo6UYw==)
    access-time: 3600000 # 60분
    refresh-time: 2628000000 # 한달
    issuer: sch