spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todo_project?serverTimezone=Asia/Seoul
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

    show-sql: true
    open-in-view: false

    hibernate:
      ddl-auto: create