spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todo_project?serverTimezone=Asia/Seoul
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

    show-sql: true
    open-in-view: false

    hibernate:
      ddl-auto: create

jwt:
  token:
    header: Authorization
    secret: ENC(WudfJ8URqcBNKztOgvlzhpFX2yV5BTBJ3ZnM+vOnL4EgiLgraeYEF+Ncb9nS0GsEMcyyR7swImbFI2V1FQ3w5Q==)
    access-time: 3600000 # 60분
    refresh-time: 2628000000 # 한달
    issuer: sch